org.gradle.jvmargs=-Xmx1G

minecraft_version=26.1.2
loader_version=0.19.3
kotlin_loader_version=1.13.13+kotlin.2.4.10

mod_version=26.1.2-1.0.3
maven_group=org.wolmics
archives_base_name=soundboardplus

# Dependencies
fabric_api_version=0.155.2+26.1.2
voicechat_api_version=2.6.20
voicechat_mod_version=2.6.22+26.1.2
modmenu_version=18.0.0

jlayer_version=1.0.1