org.gradle.jvmargs=-Xmx1G

minecraft_version=26.2
loader_version=0.19.3
kotlin_loader_version=1.13.12+kotlin.2.4.0

mod_version=26.2-1.0.2
maven_group=org.wolmics
archives_base_name=soundboardplus

# Dependencies
fabric_api_version=0.152.1+26.2
voicechat_api_version=2.6.13
voicechat_mod_version=2.6.18+26.2
modmenu_version=20.0.0-beta.2

jlayer_version=1.0.1