org.gradle.jvmargs=-Xmx1G

minecraft_version=26.1.2
loader_version=0.19.2
kotlin_loader_version=1.13.11+kotlin.2.3.21

mod_version=26.1.2-1.0.2
maven_group=org.wolmics
archives_base_name=soundboardplus

# Dependencies
fabric_api_version=0.151.0+26.1.2
voicechat_api_version=2.6.0
voicechat_mod_version=2.6.16+26.1.2
modmenu_version=18.0.0-alpha.8

jlayer_version=1.0.1